[mypy]
mypy_path = .:src
ignore_missing_imports = True

[mypy-treetable,torchaudio.*,diffq,yaml,tqdm,lameenc,musdb,museval,openunmix.*,einops,xformers.*,soundfile,matplotlib.*,scipy.*]
ignore_missing_imports = True
